stages:
  - build
  - test

build-job:
  stage: build
  image: rust:latest
  script:
    - cargo build --release

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test --verbose
  only:
    - main